import { useEffect,useState } from "react";
import { ScrollView,Text,View } from "react-native";
import { useLocalSearchParams,router } from "expo-router";
import { Feather } from "@expo/vector-icons";
import Spinner from "../../../components/ui/Spinner";
import Button from "../../../components/ui/Button";
import { apiFetch } from "../../../lib/api";
import type { PerceptionAnalytics } from "../../../types/models";
export default function PerceptionAnalyticsScreen(){const{id}=useLocalSearchParams<{id:string}>();const[data,setData]=useState<PerceptionAnalytics|null>(null);const[error,setError]=useState<string|null>(null);useEffect(()=>{apiFetch<PerceptionAnalytics>(`/api/analytics/perceptions/${id}`).then(setData).catch(e=>setError(e instanceof Error?e.message:"Analytics unavailable"))},[id]);if(!data&&!error)return <View className="flex-1 items-center justify-center bg-background"><Spinner/></View>;if(error)return <View className="flex-1 items-center justify-center gap-3 bg-background px-6"><Feather name="lock" size={24} color="#8b91a0"/><Text className="text-center font-sans text-sm text-foreground-muted">{error}</Text><Button label="Back" variant="outline" onPress={()=>router.back()}/></View>;return <ScrollView className="flex-1 bg-background" contentContainerClassName="px-5 pb-12 pt-14"><Text className="font-sans-semibold text-2xl text-foreground">Perception analytics</Text><Text className="mt-1 font-sans text-sm text-foreground-subtle">Observed response to this specific perception · {data.period_days} days</Text><View className="mt-6 flex-row flex-wrap gap-3">{[["Likes",data.likes],["Comments",data.comments],["Views",data.views],["Shares",data.shares],["Participants",data.unique_participants]].map(([label,value])=><View key={String(label)} className="w-[47%] rounded-card border border-border-hairline bg-surface p-4"><Text className="font-mono text-2xl text-foreground">{value}</Text><Text className="mt-1 font-sans text-xs uppercase tracking-wider text-foreground-subtle">{label}</Text></View>)}</View><View className="mt-5 rounded-card border border-border-hairline bg-surface p-4"><Text className="font-sans-semibold text-base text-foreground">Where interaction came from</Text>{data.top_countries.length===0?<Text className="mt-2 font-sans text-sm text-foreground-subtle">No geographic interaction data yet.</Text>:data.top_countries.map(item=><View key={item.country_code} className="flex-row justify-between border-b border-border-hairline py-3"><Text className="font-sans text-foreground">{item.country_code}</Text><Text className="font-mono text-foreground-muted">{item.interactions}</Text></View>)}</View><View className="mt-5 rounded-card border border-border-hairline bg-surface p-4"><Text className="font-sans-semibold text-base text-foreground">Methodology</Text>{data.methodology.map(item=><Text key={item} className="mt-2 font-sans text-sm leading-5 text-foreground-muted">• {item}</Text>)}</View></ScrollView>}
